# render.yaml — PHP web + MariaDB için tam sürüm
services:
  - type: web
    name: binancetr-web
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: mariadb
          property: host
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: appdb
      - key: DB_USER
        value: appuser
      - key: DB_PASSWORD
        sync: false

  - type: private_service
    name: mariadb
    env: docker
    plan: starter
    dockerfilePath: ./infra/mariadb/Dockerfile
    autoDeploy: true
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: appuser
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_ROOT_PASSWORD
        sync: false
