# render.yaml — PHP web + MariaDB (pserv)
services:
  - type: web
    name: binancetr-web
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: mariadb          # aşağıdaki pserv'in name'i ile aynı
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: mariadb
          property: port
      - key: DB_NAME
        value: appdb
      - key: DB_USER
        value: appuser
      - key: DB_PASSWORD
        sync: false             # Render panelinden gizli olarak girilecek

  - type: pserv
    name: mariadb               # web tarafında referans verdiğimiz pserv adı
    env: docker
    plan: starter
    dockerfilePath: ./infra/mariadb/Dockerfile
    autoDeploy: true
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
      - key: MYSQL_DATABASE
        value: appdb
      - key: MYSQL_USER
        value: appuser
      - key: MYSQL_PASSWORD
        sync: false             # Render panelinden gizli olarak girilecek
      - key: MYSQL_ROOT_PASSWORD
        sync: false             # Render panelinden gizli olarak girilecek
